export const DEEP_REGISTRY_DASHBOARD_SELECTORS = {
  appRoot: 'app-layout',
  sidebarShell: 'app-sidebar',
  topbarShell: 'app-topbar',
  layoutWrapper: '.layout-wrapper',
  layoutMain: '.layout-main',
  layoutContent: '.layout-content',
  pageBody: '.page-body.dashboard',
  sidebar: '.sidebar',
  brandLink: '.logo-home-button',
  brandLogo: '.logo-home-button img',
  backButton: '.back-btn',
  sidebarHeader: '.sidebar-header',
  sidebarNav: '.sidebar-nav',
  menuList: '.menu-list',
  menuItem: '.menu-item',
  menuLink: '.menu-link',
  menuLabel: '.menu-label',
  submenu: '.submenu',
  submenuLink: '.submenu-link',
  sidebarFooter: '.sidebar-footer',
  userProfile: '.user-profile',
  userName: '.user-name',
  userRole: '.user-role',
  userAvatar: '.user-avatar',
  sidebarToggle: '.menu-toggle-btn',
  searchInput: '.search-bar input',
  themeToggle: '.theme-toggle-btn',
  languageButtons: '.lang-pill-btn',
  langPill: '.lang-pill',
  notificationButton: '.notification-btn',
  themeConfigButton: '.theme-config-btn',
  profileAvatar: '.profile-avatar',
  breadcrumb: '.breadcrumb',
  breadcrumbModule: '.breadcrumb-module',
  breadcrumbItem: '.breadcrumb-item',
  topbarActions: '.topbar-right',
  topbarLeft: '.topbar-left',
  hero: '.registry-hero',
  kicker: '.registry-kicker',
  pageTitle: '.page-title',
  pageSubtitle: '.page-subtitle',
  registryVisual: '.registry-d3-visual',
  kpiCards: '.kpi-card',
  kpiTitles: '.kpi-title',
  kpiValues: '.kpi-value',
  kpiChanges: '.kpi-change',
  chartCards: '.chart-card',
  summaryCard: '.summary-card',
  pendingValidationChart: '.pending-validation-d3',
  vesselStatisticsCard: '.vessel-statistics-card',
  vesselStatCards: '.vessel-stat-card',
  vesselTotalPill: '.vessel-total-pill',
  vesselDonutCharts: '.vessel-donut-chart',
  companyUsersCard: '.company-users-card',
  companyPeriodButtons: '.company-period-filter button',
  companyInput: '.company-filter input',
  companyUsersChart: '.company-users-d3-chart',
  partyDashboardGrid: '.party-dashboard-grid',
  partyChartCards: '.party-chart-card',
  partyD3Charts: '.party-d3-chart',
  deepRegistrySubtitle: '.registry-hero .page-subtitle',
};
